app = "my-saiki-agent"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  FRONTEND_PORT = "3000"
  API_PORT = "3000"
  API_URL = "http://localhost:3000"
  FRONTEND_URL = "http://localhost:3000"
  NEXT_PUBLIC_API_URL = "/api"
  NEXT_PUBLIC_WS_URL = "wss://my-saiki-agent.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512


